version: 2.1

orbs:
  win: circleci/windows@2.2.0

# machine:
#   pre:
#     - mkdir ~/.cache/yarn

# dependencies:
#   cache_directories:
#     - ~/.cache/yarn
jobs:
  build:
    executor: win/default
    steps:
      - checkout

      - run:
          name: Setup Node.js
          command: |
            nvm install $(Get-Content .nvmrc).replace( 'v', '' );
            nvm use $(Get-Content .nvmrc).replace( 'v', '' );

      - run: 
          name: Install Yarn
          command: |
            npm i -g yarn

      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --nonInteractive --frozen-lockfile --cache-folder ~/.cache/yarn
   
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
            
      - run: 
          name: Lint
          command: |
            yarn run lint:ci

      - run: 
          name: Build
          command: |
            yarn build

      - run: 
          name: Test
          command: |
            yarn test:ci

      - run: 
          name: Build
          command: |
            yarn build