version: 2.1

orbs:
  win: circleci/windows@2.2.0

jobs:
  build:
    executor: win/default
    steps:
      - checkout

      - run:
          name: Install Docker Compose
          command: |
            curl -L https://github.com/docker/compose/releases/download/1.25.3/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose

      - run: 
          name: Check docker compose version
          command: |
            docker-compose version

      - run:
          name: Setup Node.js
          command: |
            nvm install $(Get-Content .nvmrc).replace( 'v', '' );
            nvm use $(Get-Content .nvmrc).replace( 'v', '' );

      - run: 
          name: Install Yarn
          command: |
            npm i -g yarn

      - run: 
          name: Set Yarn cache dir
          command: |
            yarn config set cache-folder ~/.cache/yarn

      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      
      - run:
          name: Install Dependencies
          command: yarn install --nonInteractive --frozen-lockfile
   
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
            
      - run: 
          name: Lint
          command: |
            yarn run lint:ci

      - run: 
          name: Build
          command: |
            yarn build

      - run: 
          name: Test
          command: |
            yarn test:ci

      - run: 
          name: Build
          command: |
            yarn build